<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta charset="utf-8" />
  <title>BeLaws: interface naar geconsolideerde wetgeving van België</title>
  <link rel="stylesheet" href="/vendor/layout-default.css" />
  <link rel="stylesheet" href="/css/reset.css" />
  <link rel="stylesheet" href="/css/design.css" />
  <meta name = "robots" content = "index, follow"/>
  <meta name="revisit-after" content="31 days" />
  <meta name="language" content="nl,fr" /> 
  <meta name="content-language" content="nl,fr" /> 
  <meta http-equiv="content-language" content="nl,fr" />
  <meta name="classification" content="database" />
  <meta name="distribution" content="global" />
  <meta name="copyright" content="iRail VZW 2014" />
  <meta name="page-topic" content="belgisch staatsblad" />
  <meta name="version" content="v0.04" />
  <meta name="keywords" lang="nl" content="wet, opzoeken, belgisch, staatsblad, wetgeving, irail, belaws, koninklijk besluit" />
  <meta name="description" content="BeLaws is een web 2.0 interface naar de geconsolideerde belgische wetgeving" lang="nl" />
  <script src="/vendor/jquery-1.6.1.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="/vendor/jquery.cookie.js" type="text/javascript" charset="utf-8"></script>
  <script src="/js/script.js" charset="utf-8"></script>

  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="http://belaws.be/apple-touch-icon-57x57.png" />
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://belaws.be/apple-touch-icon-114x114.png" />
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://belaws.be/apple-touch-icon-72x72.png" />
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://belaws.be/apple-touch-icon-144x144.png" />
  <link rel="apple-touch-icon-precomposed" sizes="60x60" href="http://belaws.be/apple-touch-icon-60x60.png" />
  <link rel="apple-touch-icon-precomposed" sizes="120x120" href="http://belaws.be/apple-touch-icon-120x120.png" />
  <link rel="apple-touch-icon-precomposed" sizes="76x76" href="http://belaws.be/apple-touch-icon-76x76.png" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="http://belaws.be/apple-touch-icon-152x152.png" />
  <link rel="icon" type="image/png" href="http://belaws.be/favicon-196x196.png" sizes="196x196" />
  <link rel="icon" type="image/png" href="http://belaws.be/favicon-96x96.png" sizes="96x96" />
  <link rel="icon" type="image/png" href="http://belaws.be/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="http://belaws.be/favicon-16x16.png" sizes="16x16" />
  <link rel="icon" type="image/png" href="http://belaws.be/favicon-128.png" sizes="128x128" />
  <meta name="application-name" content="BeLaws: interface naar geconsolideerde wetgeving van België"/>
  <meta name="msapplication-TileColor" content="#FFFFFF" />
  <meta name="msapplication-TileImage" content="http://belaws.be/mstile-144x144.png" />
  <meta name="msapplication-square70x70logo" content="http://belaws.be/mstile-70x70.png" />
  <meta name="msapplication-square150x150logo" content="http://belaws.be/mstile-150x150.png" />
  <meta name="msapplication-wide310x150logo" content="http://belaws.be/mstile-310x150.png" />
  <meta name="msapplication-square310x310logo" content="http://belaws.be/mstile-310x310.png" />

  <script type="text/javascript" language="javascript" charset="utf-8">
    $(function() { belaws.frontpage.init(); })
  </script>
</head>
<body class="index">
<div class="topmenu">
    <ul class="links">
        <li class=""><span><a href="/index.html" title="The homescreen of the user interface">Home</a></span></li>
        <li class=""><span><a href="/app.html" title="BeLaws Web Application">Webapp</a></span></li>
        <li class=""><span><a href="/statistics/index.html" title="Database statistics">Statistics</a></span></li>
        <li class=""><span><a href="/developer/doc/api.v1.html" title="Documentation">Documentation</a></span></li>
        <li class=""><span><a href="http://forum.belaws.be" title="Forum">Forum</a></span></li>
    </ul>
</div>

<div class="border">
    <div>
        <div class="b"></div>
        <div class="y"></div>
        <div class="r"></div>
    </div>
</div>

<div id="main">
    <center>
        <div class="ltxt logotxt">Geconsolideerde<br>Wetgeving</div>
        <div id="belaws-logo"></div>
        <div class="rtxt logotxt">Législation<br>consolidée</div>
        <form method="get" action="/search.phtml">
            <div id="q_wrapper">
            <input type="text" name="q" value="" id="q"/>
            </div>
            <input type="hidden" name="lang" value="nl" id="lang"/>
            <input type="submit" value="BeLaws zoeken" id="search"/>
            <input type="submit" value="Open in webapp" id="direct"/>
        </form>
        <p class="lang"><a href="/index.html?lang=nl" rel="nl">Nederlands</a> <a href="/index.html?lang=fr" rel="fr">Fran&ccedil;ais</a></p>
        <br>
        <p style="font-size: small"> &copy; 2011 - 2014 <a href="http://okfn.be" title="Open Knowledge Foundation Belgium vzw/asbl">okfn.be vzw/asbl</a></p>
    </center>
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23301483-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>
