<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta charset="utf-8" />
  <title>BeLaws: <!--{title}--></title>
  <link rel="stylesheet" href="/vendor/layout-default.css" />
  <link rel="stylesheet" href="/css/reset.css" />
  <link rel="stylesheet" href="/css/design.css" />
  <meta name = "robots" content = "index, follow"/>
  <meta name="revisit-after" content="31 days" />
  <meta name="language" content="nl" /> 
  <meta name="content-language" content="nl" /> 
  <meta http-equiv="content-language" content="nl" />
  <meta name="classification" content="database" />
  <meta name="distribution" content="global" />
  <meta name="copyright" content="iRail VZW 2011" />
  <meta name="page-topic" content="belgisch staatsblad" />
  <meta name="version" content="v0.04" />
  <meta name="keywords" lang="nl" content="wet, opzoeken, belgisch, staatsblad, wetgeving, irail, belaws, koninklijk besluit" />
  <meta name="description" content="BeLaws is een web 2.0 interface naar het Belgische staatsblad" lang="nl" />
  <script src="/vendor/jquery-1.6.1.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="/vendor/jquery.cookie.js" type="text/javascript" charset="utf-8"></script>
  <script src="/js/script.js" charset="utf-8"></script>
  <script type="text/javascript" language="javascript" charset="utf-8">
    $(function() { belaws.searchpage.init(); })
  </script>
</head>
<body class="search">
<div class="topmenu">
    <p style="position: absolute; right: 5px; top: 10px; margin:0; " class="lang"><a href="" rel="nl">Nederlands</a> <a href="" rel="fr">Fran&ccedil;ais</a></p>
    <ul class="links">
        <li class=""><span><a href="/index.html" title="The homescreen of the user interface">Home</a></span></li>
        <li class=""><span><a href="/app.html" title="BeLaws Web Application">Webapp</a></span></li>
        <li class=""><span><a href="/statistics/index.html" title="Database statistics">Statistics</a></span></li>
        <li class=""><span><a href="/developer/doc/api.v1.html" title="Documentation">Documentation</a></span></li>
    </ul>
</div>

<div class="border">
    <div>
        <div class="b"></div>
        <div class="y"></div>
        <div class="r"></div>
    </div>
</div>

<div id="main">
        <div id="belaws-logo"></div>
        <form>
            <div id="q_wrapper">
            <input type="text" name="q" value="" id="q"/>
            </div>
            <input type="hidden" name="lang" value="" id="lang"/>
            <input type="submit" value="BeLaws zoeken" id="search"/>
        </form>
</div>

<div id="results">
    <!--{#rows}-->
    <div class="result">
        <h3><a href="/<!--{lang}-->/<!--{docuid}-->/"><!--{cat}--> <!--{docuid}--></a></h3>
        <p><!--{{title}}--></p>
    </div>
    <!--{/rows}-->
    <!--{#norows}-->
    <div class="result warning">
        <p>0 results found. Do you think this is wrong? please provide feedback</p>
    </div>
    <!--{/norows}-->
    
</div>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23301483-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>
